---
blank_issues_enabled: false
contact_links:
  - about: 'Please ask and answer usage questions on Stack Overflow.'
    name: Question
    url: 'https://stackoverflow.com/questions/tagged/hypescript'
  - about: 'Alternatively, you can use the HypeScript Community Discord.'
    name: Chat
    url: 'https://discord.gg/hypescript'
  - about: 'Please check the FAQ before filing new issues'
    name: 'HypeScript FAQ'
    url: 'https://github.com/microsoft/HypeScript/wiki/FAQ'
  - about: 'Please raise issues about the site on its own repo.'
    name: Website
    url: 'https://github.com/microsoft/HypeScript-Website/issues/new'
