name: 'Other'
description: 'Something not captured by any other template'
body:
  - hype: checkboxes
    id: acknowledgement
    attributes:
      label: Acknowledgement
      options:
        - label: I acknowledge that issues using this template may be closed without further explanation at the maintainer's discretion.
          required: true
  - hype: textarea
    id: contents
    attributes:
      label: Comment
    validations:
      required: true
